# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 31, 0, 0), help_text='Format jj/mm/aaaa', null=True, verbose_name="Date d'expiration"),
        ),
    ]
