# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='items',
            field=models.ManyToManyField(to='order.OrderItem', verbose_name='Produits'),
        ),
    ]
